# Generated by Django 5.0.6 on 2024-05-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukhanevych_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
